name: CI
on: [push]
jobs:
  ci:
    strategy:
      matrix:
        platform: [x64, x86]
    runs-on: windows-latest
    steps:
      - name: Install Cygwin
        uses: me-and/setup-cygwin@7119423
        with:
          platform: ${{ matrix.platform }}
          packages: >
            asciidoc bash-completion bash-completion-devel cygport dblatex
            docbook-xml45 docbook2X gcc-core gettext gettext-devel git gnupg
            gnupg2 libcurl-devel libexpat-devel libiconv libiconv-devel
            libpcre-devel libssl-devel perl-Authen-SASL-XS perl-DBD-SQLite
            perl-IO-Socket-SSL perl-IO-Tty perl-MailTools perl-Net-SMTP-SSL
            perl-TermReadkey perl-Test-Harness perl-XML-SAX perl-YAML-Tiny
            pkg-config subversion-perl time xmlto zlib-devel
      - name: Store choco logs
        uses: actions/upload-artifact@v2
        with:
          name: choco-logs
          path: 'C:\ProgramData\chocolatey\logs\'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cygport download
        run: "C:\\tools\\cygwin\\bin\\bash.exe -c 'cygport git.cygport download'"
      - name: Cygport prep
        run: "C:\\tools\\cygwin\\bin\\bash.exe -c 'cygport git.cygport prep'"
      - name: Cygport compile
        run: "C:\\tools\\cygwin\\bin\\bash.exe -c 'cygport git.cygport compile'"
      - name: Cygport test
        run: "C:\\tools\\cygwin\\bin\\bash.exe -c 'cygport git.cygport test'"
      - name: Cygport install
        run: "C:\\tools\\cygwin\\bin\\bash.exe -c 'cygport git.cygport install'"
      - name: Cygport package
        run: "C:\\tools\\cygwin\\bin\\bash.exe -c 'cygport git.cygport package'"
