name: CI
on: [push]
jobs:
  ci:
    runs-on: windows-latest
    steps:
      - name: Install Cygwin
        uses: egor-tensin/setup-cygwin@v1
        with:
          platform: x64
          packages: bash-completion
