name: CI
on: [push, pull_request]
jobs:
  ci:
    strategy:
      matrix:
        platform: [x64, x86]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load packages to install
        id: cyg-package-list
        run: |
          $pkgs = Get-Content -Path .\build-requires.txt
          echo "::set-output name=packages::$pkgs"
      - name: Install Cygwin
        uses: me-and/setup-cygwin@test-blocking
        with:
          platform: ${{ matrix.platform }}
          packages: ${{ steps.cyg-package-list.outputs.packages }}
      - name: Generate cygcheck output
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygcheck -srv >/var/log/cygcheck.out'
        if: always()
      - name: Store choco logs
        uses: actions/upload-artifact@v2
        with:
          name: choco-logs
          path: 'C:\ProgramData\chocolatey\logs\'
        if: always()
      - name: Store Cygwin logs
        uses: actions/upload-artifact@v2
        with:
          name: cygwin-logs
          path: 'C:\tools\cygwin\var\log\'
        if: always()
      - name: Cygport download
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygport git.cygport download'
      - name: Cygport prep
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygport git.cygport prep'
      - name: Cygport compile
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygport git.cygport compile'
      - name: Cygport test
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygport git.cygport test'
      - name: Cygport install
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygport git.cygport install'
      - name: Cygport package
        run: |
          C:\tools\cygwin\bin\bash.exe -c 'cygport git.cygport package'
